name: Repository validation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  repository-validation:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Check out repository
        # v4.3.1
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - name: Validate repository
        run: ./validate.sh
